version: "3"
services:
  exercise5:
    build: .
    ports:
      - "9005:9005"
    depends_on:
      - mongodb
      - replica
      - redis
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27018:27017
  replica:
    image: mongo
    command: mongod --port 27018
    volumes:
      - ./data/replica:/data/replica
    ports:
      - 27019:27018
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: always
