version: "3"
services:
  exercise6:
    build: .
    ports:
      - "9006:9006"
    links:
      - messageapp
      - mongodb
      - replica
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  replica:
    image: mongo
    command: mongod --port 27018
    volumes:
      - ./data/replica:/data/replica
    ports:
      - 27018:27018
